### ISSUE TITLE
The bower_components/ path is missing from the source code

### ISSUE THREAD

**Issue by prushforth** [googlecodelabs/polymer-first-elements#10]
The bower_components directory is not referenced by the cloned code from the repo, so you have to edit the paths to make the examples as described by [this page](http://www.code-labs.io/codelabs/polymer-first-elements/index.html?index=..%2F..%2Fpolymer-summit&viewga=UA-39334307-12#2) work.

Cheers

**Comment by arthurevans** [comment]
If you use Chrome Dev Editor or run the examples using `polyserve`, the demo should run correctly. This repo should really have a README though to point people in the right direction.

**Comment by arthurevans** [comment]
Added a README. Hopefully this is clearer now.
