### ISSUE TITLE
Comment incorrect

### ISSUE THREAD

**Issue by paulistoan** [googlecodelabs/polymer-first-elements#5]
The following comment: 

> If you run the demo now, you won't see any icon at all; there's no default value for the toggleIcon property. You can set it programmatically, like this:

is incorrect, as the provided icon-toggle-demo.html file provides a `toggle-icon` value for all `icon-toggle` elements it instantiates.

Additionally, the following logic:

``` javascript
toggleIcon: String
```

seemed redundant as the property seemed to be propagated to the template even without having explicitly declared it in the Polymer() call.

**Comment by arthurevans** [comment]
@paulistoan Thanks, I'll clarify this section. 

Polymer is doing something unexpected (to me) here, so I've raised a ticket over there: https://github.com/Polymer/polymer/issues/2440

You're right that the `toggleIcon: String` line is unrelated to the data binding; it's purportedly in there to expose the property `toggleIcon` as an attribute, `toggle-icon` ... However, it appears that it's already being exposed as a side effect of adding the binding.

**Comment by arthurevans** [comment]
Codelab is updated and hopefully clearer now. Thanks for the report!
