### ISSUE TITLE
title attribute everywhere

### ISSUE THREAD

**Issue by DhatriM** [googlecodelabs/polymer-first-elements#9]
Minor glitch. But the whole tutorial page shows the title attribute string. It becomes irritating to move the mouse over some text and the title would appear there, telling me what page I am on. Eg : Begin here : Your first Polymer element.

**Comment by arthurevans** [comment]
Where are you seeing this? On the codelab page, or when running the demo?

**Comment by arthurevans** [comment]
Thanks for the report. This appears to be a problem with the codelab infrastructure rather than this particular codelab, so I'm closing this and opening a bug against the codelab components: googlecodelabs/codelab-components#6
